export const honneyQuestions = [
    { label: 'Tenho fama de dizer o que penso claramente e sem rodeios.', value: 'P' },
    { label: 'Estou seguro do que é bom e do que é mau, do que está bem e do que está mal.', value: 'T' },
    { label: 'Muitas vezes ajo sem olhar as consequências.', value: 'A' },
    { label: 'Normalmente, resolvo os problemas metodicamente e passo a passo.', value: 'T' },
    { label: 'Creio que a formalidade corta e limita a atuação espontânea das pessoas.', value: 'A' },
    { label: 'Interessam-me saber quais são os sistemas de valores dos outros e com que critérios atuam.', value: 'T' },
    { label: 'Penso que agir intuitivamente pode ser sempre tão válido quanto atuar reflexivamente.', value: 'A' },
    { label: 'Creio que o mais importante é que as coisas funcionem.', value: 'P' },
    { label: 'Procuro estar atento ao que acontece aqui e agora.', value: 'A' },
    { label: 'Agrada-me quando tenho tempo para preparar meu trabalho e realizá-lo com consciência.', value: 'R' },
    { label: 'Estou seguindo, porque quero uma ordem na alimentação, no estudo, fazendo exercícios regularmente.', value: 'T' },
    { label: 'Quando escuto uma nova ideia, em seguida começo a pensar como colocá-la em prática.', value: 'P' },
    { label: 'Prefiro as ideias originais e novas, mesmo que não sejam práticas.', value: 'A' },
    { label: 'Admito e ajusto-me às normas somente se servirem para atingir meus objetivos.', value: 'P' },
    { label: 'Normalmente me dou melhor com pessoas reflexivas e pior com pessoas demasiado espontâneas e imprevisíveis.', value: 'T' },
    { label: 'Escuto com mais frequência do que falo.', value: 'R' },
    { label: 'Prefiro as coisas estruturadas às desordenadas.', value: 'T' },
    { label: 'Quando possuo qualquer informação, trato de interpretá-la bem antes de manifestar alguma conclusão.', value: 'R' },
    { label: 'Antes de fazer algo, estudo com cuidado suas vantagens e inconvenientes.', value: 'R' },
    { label: 'Estimula-me o fato de fazer algo novo e diferente.', value: 'A' },
    { label: 'Quase sempre procuro ser coerente com meus critérios e escala de valores; tenho princípios e os sigo.', value: 'T' },
    { label: 'Em uma discussão, não gosto de rodeios.', value: 'P' },
    { label: 'Não me agrada envolvimento afetivo no ambiente de trabalho; prefiro manter relações distantes.', value: 'T' },
    { label: 'Gosto mais das pessoas realistas e concretas do que das teóricas.', value: 'P' },
    { label: 'É difícil ser criativo e romper estruturas.', value: 'T' },
    { label: 'Gosto de estar perto de pessoas espontâneas e divertidas.', value: 'A' },
    { label: 'A maioria das vezes expresso abertamente como me sinto.', value: 'A' },
    { label: 'Gosto de analisar e esmiuçar as coisas.', value: 'R' },
    { label: 'Incomoda-me o fato de as pessoas não levarem as coisas a sério.', value: 'T' },
    { label: 'Atrai-me experimentar e praticar as últimas técnicas e novidades.', value: 'P' },
    { label: 'Sou cautelosa na hora de tirar conclusões.', value: 'R' },
    { label: 'Prefiro contar com o maior número de fontes de informação; quanto mais dados houver para refletir, melhor.', value: 'R' },
    { label: 'Tenho tendência a ser perfeccionista.', value: 'T' },
    { label: 'Prefiro ouvir a opinião dos outros antes de expor a minha.', value: 'R' },
    { label: 'Gosto de levar a vida espontaneamente e não ter de planejá-la.', value: 'A' },
    { label: 'Nas discussões, gosto de observar como atuam os outros participantes.', value: 'R' },
    { label: 'Sinto-me incomodado com as pessoas caladas e demasiadamente analíticas.', value: 'A' },
    { label: 'Julgo com frequência as ideias dos outros por seu valor prático.', value: 'P' },
    { label: 'Angustio-me se me obrigam a acelerar muito o trabalho para cumprir um prazo.', value: 'R' },
    { label: 'Nas reuniões apoio as ideias práticas e realistas.', value: 'P' },
    { label: 'É melhor aproveitar o momento presente do que deleitar-se pensando no passado ou no futuro.', value: 'A' },
    { label: 'Incomodam-me as pessoas que sempre desejam apressar as coisas.', value: 'R' },
    { label: 'Apoio ideias novas e espontâneas nos grupos de discussão.', value: 'A' },
    { label: 'São mais consistentes as decisões fundamentadas em minuciosa análise do que as baseadas em intuição.', value: 'R' },
    { label: 'Detecto frequentemente a inconsistência e os pontos frágeis nas argumentações dos outros.', value: 'T' },
    { label: 'Creio que é preciso transpor as normas muito mais vezes do que cumpri-las.', value: 'A' },
    { label: 'Frequentemente, percebo outras formas melhores e mais práticas de fazer as coisas.', value: 'P' },
    { label: 'No geral, falo mais do que escuto.', value: 'A' },
    { label: 'Prefiro distanciar-me dos fatos e observá-los a partir de outras perspectivas.', value: 'R' },
    { label: 'Estou convencido de que deve impor-se a lógica e a razão.', value: 'T' },
    { label: 'Gosto de buscar novas experiências.', value: 'A' },
    { label: 'Gosto de experimentar e aplicar as coisas.', value: 'P' },
    { label: 'Penso que devemos chegar logo ao âmago, ao centro das questões.', value: 'P' },
    { label: 'Procuro sempre chegar a conclusões e ideias claras.', value: 'T' },
    { label: 'Prefiro discutir questões concretas e não perder tempo com falas vazias.', value: 'R' },
    { label: 'Incomodo-me quando dão explicações irrelevantes e incoerentes.', value: 'P' },
    { label: 'Comprovo antes se as coisas funcionam realmente.', value: 'P' },
    { label: 'Faço vários borrões antes da redação final de um trabalho.', value: 'R' },
    { label: 'Sou consciente de que nas discussões ajudo a manter os outros centrados nos temas, evitando divagações.', value: 'P' },
    { label: 'Observo que, com frequência, sou um dos mais objetivos e ponderados nas discussões.', value: 'T' },
    { label: 'Quando algo vai mal, não dou importância e trato de fazê-lo melhor.', value: 'A' },
    { label: 'Desconsidero as ideias originais e espontâneas se não as percebo práticas.', value: 'P' },
    { label: 'Gosto de analisar diversas alternativas antes de tomar uma decisão.', value: 'R' },
    { label: 'Com frequência, olho adiante para prever o futuro.', value: 'T' },
    { label: 'Nos debates e discussões prefiro desempenhar um papel secundário a ser o líder ou o que mais participa.', value: 'R' },
    { label: 'Incomodam-me as pessoas que não atuam com lógica.', value: 'T' },
    { label: 'Incomodam-me ter de planejar e prever as coisas.', value: 'A' },
    { label: 'Creio que o fim justifica os meios em muitos casos.', value: 'P' },
    { label: 'Costumo refletir sobre os assuntos e problemas.', value: 'R' },
    { label: 'O trabalho consciente me traz satisfação e orgulho.', value: 'R' },
    { label: 'Diante dos acontecimentos, trato de descobrir os princípios e teorias em que se baseiam.', value: 'T' },
    { label: 'Com o intuito de conseguir o objetivo que pretendo, sou capaz de ferir sentimentos alheios.', value: 'P' },
    { label: 'Não me importa fazer todo o necessário para que o meu trabalho seja efetivado.', value: 'P' },
    { label: 'Com frequência, sou uma das pessoas que mais anima as festas.', value: 'A' },
    { label: 'Frequentemente me aborreço com o trabalho metódico e minucioso.', value: 'A' },
    { label: 'As pessoas, com frequência, creem que sou pouco sensível a seus sentimentos.', value: 'P' },
    { label: 'Costumo deixar-me levar por minhas intuições.', value: 'A' },
    { label: 'Nos trabalhos de grupo, procuro que se sigam um método e uma ordem.', value: 'T' },
    { label: 'Com frequência, interessa-me saber o que as pessoas pensam.', value: 'R' },
    { label: 'Evito os temas subjetivos, ambíguos e pouco claros.', value: 'T' },
];